export const TODO_SUBMIT = 'TODO_SUBMIT';
export const TODO_SUBMIT_START = 'TODO_SUBMIT_START';
export const TODO_SUBMIT_SUCCESS = 'TODO_SUBMIT_SUCCESS';
export const TODO_SUBMIT_ERROR = 'TODO_SUBMIT_ERROR';

export const FETCH_TODO_START = 'FETCH_TODO_START';
export const FETCH_TODO_SUCCESS = 'FETCH_TODO_SUCCESS';
export const FETCH_TODO_ERROR = 'FETCH_TODO_ERROR';

export const REMOVE_TODO_START = 'REMOVE_TODO_START';
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';
export const REMOVE_TODO_ERROR = 'REMOVE_TODO_ERROR';

export const AUTH_START = 'SIGN_START';
export const AUTH_ERROR = 'SIGN_ERROR';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_AVATAR = 'GET_AVATAR';
export const START_INFO_RESPONSE = 'START_INFO_RESPONSE';

export const CHANGE_OPTIONS_START = 'CHANGE_OPTIONS_START';
export const CHANGE_OPTIONS_ERROR = 'CHANGE_OPTIONS_ERROR';
export const CHANGE_OPTIONS_SUCCESS = 'CHANGE_OPTIONS_SUCCESS';
