export const TODO_SUBMIT = 'TODO_SUBMIT';
export const TODO_SUBMIT_START = 'TODO_SUBMIT_START';
export const TODO_SUBMIT_SUCCESS = 'TODO_SUBMIT_SUCCESS';
export const TODO_SUBMIT_ERROR = 'TODO_SUBMIT_ERROR';

export const FETCH_TODO_START = 'FETCH_TODO_START';
export const FETCH_TODO_SUCCESS = 'FETCH_TODO_SUCCESS';
export const FETCH_TODO_ERROR = 'FETCH_TODO_ERROR';

export const REMOVE_TODO_START = 'REMOVE_TODO_START';
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';
export const REMOVE_TODO_ERROR = 'REMOVE_TODO_ERROR';
